[cli] load apicast loader
because the main APICAST_MODULE is loaded in the CLI
and it could have deprecated requires, we need to initialize the loader
that takes case of the deprecations

```
ERROR: ./src/apicast/policy_chain.lua:47: module apicast.module could not be loaded
stack traceback:
	./src/apicast/policy_chain.lua:47: in function 'build_default_chain'
	./src/apicast/policy/local_chain.lua:20: in main chunk
	[C]: in function 'require'
	./src/apicast/policy_chain.lua:76: in function 'load'
	./src/apicast/policy_chain.lua:47: in function 'default'
	./src/apicast/cli/environment.lua:57: in main chunk
	[C]: in function 'require'
	./src/apicast/cli/command/start.lua:12: in main chunk
```